#! /bin/bash

timeout=1;
pings_cnt=0
usage="Usage: $(basename $0) [-c ###] [-t ###] [-u user-name] exe-name";

int_opt_validation() {
    reg='^[0-9]+$'
    if ! [[ $1 =~ $reg ]] ; then
        echo -e "Error: Not a number - '$1'\n$usage";  
        exit 1
    fi            
}

while getopts "c::t::u::" opts 2>/dev/null
do
    case $opts in
        c)
            int_opt_validation $OPTARG
            pings_amount=$OPTARG
            ;;
        t)
            int_opt_validation $OPTARG
            timeout=$OPTARG
            ;;
        u)
            user_name=$OPTARG
            ;;
        ?)
            echo -e "Error: An invalid option has been entered.\n$usage" 
            exit 1
            ;; 
    esac
done
shift $((OPTIND-1))
[[ $# != 1 ]] &&  echo $usage && exit 1

ping_for="Pinging '$1' for"
[[ $user_name ]] && ping_for+=" user '$user_name'" || ping_for+=" any user" 
echo "${ping_for}"

ping_processes() {
    [ $user_name ] && user="-u $user_name"
    pings_count=$(pgrep $user $1 | wc -l)
    echo "$1: ${pings_count} instance(s)..." 
}

while [[ true ]]; 
do    
    ping_processes $1;
    sleep $timeout;
    pings_cnt=$(($pings_cnt + 1))
    [[ $pings_cnt == $pings_amount ]] && break 
done
